# Generated by Django 4.0 on 2021-12-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('info', models.CharField(default='No info!', max_length=255, null=True)),
                ('img_link', models.CharField(default='No image link!', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('info', models.CharField(default='No info!', max_length=255, null=True)),
                ('additional_info', models.CharField(default='No additional info!', max_length=500, null=True)),
                ('img_link', models.CharField(default='No image link!', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default='No date yet!', null=True)),
                ('lineup', models.CharField(default='No lineup!', max_length=500, null=True)),
                ('additional_info', models.CharField(default='No additional info!', max_length=1000, null=True)),
                ('tickets', models.CharField(default='No tickets yet!', max_length=1000, null=True)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.artist')),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.location')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Artist_Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.artist')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.genre')),
            ],
        ),
    ]
