# Generated by Django 4.0 on 2022-01-03 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('data', '0003_spotifytoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_genre',
            unique_together={('uid', 'gid')},
        ),
    ]
