# Generated by Django 4.0 on 2022-01-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_artist_genre_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_SpotifyID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=50)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.artist')),
            ],
        ),
    ]
